#!/usr/bin/python3
"""Factorize as many numbers as possible into
   a product of two smaller numbers"""

import math
from sys import argv


def factorize(num):

    """gets the factors of num"""
    i = 2

    if num < 2:
        return

    while num % i:
        i += 1

    print("{}={}*{}".format(num, i, num / i))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            product = int(line.split('\n')[0])
            factorize(product)
            line = file.readline()

except:
    pass
